### ISSUE TITLE
Battle System

### ISSUE THREAD

**Issue by 133794m3r** [133794m3r/itp298_capstone#10]
Basic battle system done. This issue will make sure that a person can undertake a battle.

# Tasks To Be Completed
Lists the basic things that should be done for the system to work.
## Basic Ones
- [x] Menu system implemented
- [x] Input validation
- [x] Mob "AI" implemented.
# Better UX
- [x] Partial Refreshes during menu
- [x] Shows messages in Menu and then redraws menu
# Advanced
- [x] Checks for Death of player/mob
- [x] Returns who died.
- [x] Handles awarding rewards post battle

## Tests
- [x] Basic battle carried out via user input.
- [x] Shows who died/won.

**Comment by 133794m3r** [comment]
This issue is currently blocked from being started by PR #19 as I wait on @NathanielMullins to review the code. As such no code can be done until the baes actor/mob/player classes are in master as all other branches branch off of master.

**Comment by 133794m3r** [comment]
No longer blocked by #19 that PR is now in master. Now time to figure out a battle menu or some sorts.
