### ISSUE TITLE
Classes Started and mostly done

### ISSUE THREAD

**Issue by 133794m3r** [133794m3r/itp298_capstone#3]
This issue will track the various classes as they're being started on. It'll be a grouop issue that'll track the other ones.

- [x] Actor class tracked via #2
- [x] Mob Class tracked via #16 
- [x] Player Class tracked via #4
- [x] Item class tracked via #18
- [ ] Map class tracked via #11
- [ ] Basic class tests tracked via #7

**Comment by 133794m3r** [comment]
Me and Nathaniel will be tracking this issue as it goes over all of the issues. Thus it's going to be us all.
